<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>haaa</groupId>
    <artifactId>ShitBot</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>ShitBot</name>

    <modules>
        <module>ShitBotCore</module>
        <module>ShitBotBungee</module>
        <module>ShitBotSpigot</module>
        <module>ShitBotVelocity</module>
    </modules>
</project>
