name: ShitBotSpigot
version: '${project.version}'
main: haaa.shitbotspigot.ShitBotSpigot
folia-supported: true
authors: [ H_aaa ]
commands:
  shitbot:
    description: ShitBot management command
    aliases: [ sbot ]
    usage: /shitbot status|reload|image|migrate easybot [EasyBot.db]
permissions:
  shitbot.admin:
    description: Allows ShitBot administration
    default: op
