"use strict";
const $=s=>document.querySelector(s), state={id:null,bundle:null,sources:null,selected:null,tab:"visual",previewUrl:null};
const types=["text","image","avatar","rectangle","circle","line","progress","group","stack","grid","condition","loop"];
for(const type of types){const option=document.createElement("option");option.value=type;option.textContent=type;$("#newLayerType").append(option)}
async function api(path,options={}){options.headers={...(options.headers||{}),"X-ShitBot-Editor":"1"};const response=await fetch("/api/"+path,options);if(!response.ok){let message=response.statusText;try{message=(await response.json()).error||message}catch(_){ }throw new Error(message)}return response}
function status(message,error=false){const el=$("#status");el.textContent=message;el.style.color=error?"#ff9e9e":"#8ed9ba"}
function query(value){return encodeURIComponent(value)}
async function refreshTemplates(){const values=await (await api("templates")).json();const box=$("#templates");box.textContent="";for(const item of values){const el=document.createElement("div");el.className="template"+(item.id===state.id?" active":"");el.innerHTML=`<b>${escapeHtml(item.name||item.id)}</b><small>${escapeHtml(item.id)} · ${item.published?"v"+item.version:"draft only"}</small>`;el.onclick=()=>loadTemplate(item.id);box.append(el)}}
async function loadTemplate(id){try{status("Loading…");state.id=id;state.bundle=await (await api("template?id="+query(id))).json();state.sources=await (await api("source?id="+query(id))).json();state.selected=null;$("#templateTitle").textContent=(state.bundle.manifest.name||id)+" ("+id+")";$("#manifestSource").value=state.sources.manifest;$("#sceneSource").value=state.sources.scene;renderVersions();renderVisual();await refreshTemplates();status("Draft loaded")}catch(error){status(error.message,true)}}
function renderVersions(){const select=$("#versions");select.textContent="";for(const version of state.bundle.versions||[]){const option=document.createElement("option");option.value=version;option.textContent="Version "+version;select.append(option)}}
function layers(){return state.bundle&&Array.isArray(state.bundle.scene.layers)?state.bundle.scene.layers:[]}
function nodeAt(path){let value=state.bundle.scene.layers;for(let i=0;i<path.length;i++){value=value[path[i]];if(i+1<path.length){const key=path[++i];value=value[key]}}return value}
function parentList(path){if(path.length===1)return state.bundle.scene.layers;let value=state.bundle.scene.layers;for(let i=0;i<path.length-1;i++){value=value[path[i]];const key=path[++i];value=value[key]}return value}
function flatten(nodes,prefix=[],depth=0,out=[]){nodes.forEach((node,index)=>{const path=[...prefix,index];out.push({node,path,depth});for(const key of ["children","then","else"]){if(Array.isArray(node[key]))flatten(node[key],[...path,key],depth+1,out)}});return out}
function renderVisual(){if(!state.bundle)return;const canvas=state.bundle.scene.canvas||{},width=Number(canvas.width)||1200,height=Number(canvas.height)||675,wrap=$(".stage-wrap"),scale=Math.min(1,Math.max(.2,(wrap.clientWidth-55)/width));const stage=$("#stage");stage.style.width=width+"px";stage.style.height=height+"px";stage.style.transform=`scale(${scale})`;stage.style.marginBottom=(height*(scale-1))+"px";stage.style.background=canvas["gradient-start"]?`linear-gradient(135deg,${canvas["gradient-start"]},${canvas["gradient-end"]||canvas["gradient-start"]})`:(canvas.background||"#174c72");stage.textContent="";const flat=flatten(layers());flat.forEach(item=>drawNode(stage,item));renderLayerList(flat);renderProperties()}
function drawNode(stage,item){const n=item.node,type=n.type||"unknown";if(["condition","loop"].includes(type))return;const el=document.createElement("div");el.className="stage-node"+(samePath(item.path,state.selected)?" selected":"");el.dataset.type=type;el.style.left=(Number(n.x)||0)+"px";el.style.top=(Number(n.y)||0)+"px";el.style.width=(Number(n.width)||defaultSize(type)[0])+"px";el.style.height=(Number(n.height)||defaultSize(type)[1])+"px";el.style.opacity=n.opacity==null?1:n.opacity;if(n.fill||n.color){if(type==="text")el.style.color=n.color||"#fff";else el.style.background=n.fill||n.color}if(n.radius!=null)el.style.borderRadius=n.radius+"px";if(type==="text") {el.textContent=n.text||"Text";el.style.fontSize=(n["font-size"]||18)+"px";el.style.fontWeight=String(n["font-style"]||"").includes("bold")?"700":"400"}else if(type==="image"||type==="avatar")el.textContent=type;const handle=document.createElement("span");handle.className="resize-handle";handle.style.cssText="position:absolute;right:0;bottom:0;width:12px;height:12px;background:#ffe16b;border:2px solid #111;cursor:nwse-resize;display:"+(samePath(item.path,state.selected)?"block":"none");makeResizable(handle,item.path,el);el.append(handle);el.onclick=e=>{e.stopPropagation();state.selected=item.path;renderVisual()};makeDraggable(el,item.path);stage.append(el)}
function makeDraggable(el,path){el.onpointerdown=e=>{if(e.button!==0)return;const n=nodeAt(path),startX=e.clientX,startY=e.clientY,x=Number(n.x)||0,y=Number(n.y)||0;el.setPointerCapture(e.pointerId);el.onpointermove=move=>{const rect=$("#stage").getBoundingClientRect(),scale=rect.width/(Number(state.bundle.scene.canvas.width)||1);n.x=Math.round((x+(move.clientX-startX)/scale)/5)*5;n.y=Math.round((y+(move.clientY-startY)/scale)/5)*5;el.style.left=n.x+"px";el.style.top=n.y+"px";renderProperties()};el.onpointerup=()=>{el.onpointermove=null;el.onpointerup=null}}}
function makeResizable(handle,path,el){handle.onpointerdown=e=>{e.stopPropagation();if(e.button!==0)return;const n=nodeAt(path),startX=e.clientX,startY=e.clientY,width=Number(n.width)||defaultSize(n.type)[0],height=Number(n.height)||defaultSize(n.type)[1];handle.setPointerCapture(e.pointerId);handle.onpointermove=move=>{const rect=$("#stage").getBoundingClientRect(),scale=rect.width/(Number(state.bundle.scene.canvas.width)||1);n.width=Math.max(5,Math.round((width+(move.clientX-startX)/scale)/5)*5);n.height=Math.max(5,Math.round((height+(move.clientY-startY)/scale)/5)*5);el.style.width=n.width+"px";el.style.height=n.height+"px";renderProperties()};handle.onpointerup=()=>{handle.onpointermove=null;handle.onpointerup=null}}}
function renderLayerList(flat){const box=$("#layers");box.textContent="";flat.forEach(item=>{const el=document.createElement("div");el.className="layer"+(samePath(item.path,state.selected)?" selected":"");el.style.paddingLeft=(10+item.depth*14)+"px";el.textContent=(item.node.name||item.node.text||item.node.type||"layer").toString().slice(0,40);el.onclick=()=>{state.selected=item.path;renderVisual()};box.append(el)})}
const fieldNames=["name","x","y","width","height","text","source","fill","color","stroke-color","stroke-width","radius","opacity","font-family","font-size","font-style","align","visible","when","condition","equals","items","as","maximum-items","direction","gap","columns","column-gap","row-gap","cell-width","cell-height"];
function renderProperties(){const box=$("#fields"),area=$("#layerJson");box.textContent="";if(!state.selected){area.value="";return}const n=nodeAt(state.selected);for(const name of fieldNames){if(!(name in n)&&!["name","x","y","width","height"].includes(name))continue;const label=document.createElement("label");label.textContent=name;const input=document.createElement("input");input.value=n[name]==null?"":n[name];input.onchange=()=>{const raw=input.value;n[name]=["x","y","width","height","stroke-width","radius","opacity","font-size"].includes(name)&&raw!==""?Number(raw):raw;renderVisual()};label.append(input);box.append(label)}area.value=JSON.stringify(n,null,2)}
function defaultSize(type){if(type==="text")return[220,35];if(type==="line")return[160,2];if(type==="circle"||type==="avatar")return[80,80];if(type==="progress")return[220,20];return[180,90]}
function defaultLayer(type){const [width,height]=defaultSize(type),base={type,x:20,y:20,width,height};if(type==="text")Object.assign(base,{text:"New text","font-size":18,color:"#FFFFFFFF"});else if(type==="rectangle"||type==="circle")base.fill="#40FFFFFF";else if(type==="image"||type==="avatar")base.source="assets/example.png";else if(type==="line")Object.assign(base,{color:"#FFFFFFFF","stroke-width":2});else if(type==="progress")Object.assign(base,{value:60,maximum:100,fill:"#52C98A"});else if(type==="condition")return{type,condition:"${data.example.enabled}",then:[],else:[]};else if(type==="loop")return{type,items:"${data.example.items}",as:"item","maximum-items":20,children:[]};else Object.assign(base,{children:[]});return base}
function samePath(a,b){return !!a&&!!b&&a.length===b.length&&a.every((v,i)=>v===b[i])}
function previewBody(){return JSON.stringify({context:parseJson($("#contextData").value,"context"),data:parseJson($("#overrideData").value,"data")})}
function parseJson(text,label){try{return JSON.parse(text||"{}")}catch(error){throw new Error(label+" is invalid JSON: "+error.message)}}
async function save(){if(!state.id)return;if(state.tab==="source"){await api("source?id="+query(state.id),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({manifest:$("#manifestSource").value,scene:$("#sceneSource").value})})}else{await api("draft?id="+query(state.id),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({manifest:state.bundle.manifest,scene:state.bundle.scene})})}await loadTemplate(state.id);status("Draft saved")}
async function preview(){if(!state.id)return;await save();status("Rendering preview…");const response=await api("preview?id="+query(state.id),{method:"POST",headers:{"Content-Type":"application/json"},body:previewBody()});const blob=await response.blob();if(state.previewUrl)URL.revokeObjectURL(state.previewUrl);state.previewUrl=URL.createObjectURL(blob);$("#previewImage").src=state.previewUrl;$("#previewDialog").showModal();status("Preview ready")}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
document.addEventListener("click",async event=>{const button=event.target.closest("button");if(!button)return;try{if(button.id==="save")await save();else if(button.id==="preview")await preview();else if(button.id==="publish"){await save();const result=await(await api("publish?id="+query(state.id),{method:"POST"})).json();await loadTemplate(state.id);status("Published version "+result.version)}else if(button.id==="rollback"){const version=$("#versions").value;if(version&&confirm("Use published version "+version+"?")){await api("rollback?id="+query(state.id)+"&version="+query(version),{method:"POST"});await loadTemplate(state.id);status("Rolled back to version "+version)}}else if(button.id==="newTemplate"){const id=prompt("Template ID (lowercase letters, numbers, _ or -)");if(id){const name=prompt("Display name",id)||id;await api("template?id="+query(id),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});await loadTemplate(id)}}else if(button.id==="addLayer"){if(!state.bundle)return;const node=defaultLayer($("#newLayerType").value);layers().push(node);state.selected=[layers().length-1];renderVisual()}else if(button.id==="deleteLayer"){if(state.selected&&confirm("Delete selected layer?")){const list=parentList(state.selected),index=state.selected[state.selected.length-1];list.splice(index,1);state.selected=null;renderVisual()}}else if(button.id==="layerUp"||button.id==="layerDown"){if(state.selected){const list=parentList(state.selected),index=state.selected[state.selected.length-1],next=index+(button.id==="layerUp"?-1:1);if(next>=0&&next<list.length){[list[index],list[next]]=[list[next],list[index]];state.selected=[...state.selected.slice(0,-1),next];renderVisual()}}}else if(button.id==="applyLayerJson"){if(state.selected){const parsed=parseJson($("#layerJson").value,"layer");const list=parentList(state.selected),index=state.selected[state.selected.length-1];list[index]=parsed;renderVisual()}}else if(button.id==="resolveData"){const result=await(await api("resolve?id="+query(state.id),{method:"POST",headers:{"Content-Type":"application/json"},body:previewBody()})).json();$("#resolvedData").textContent=JSON.stringify(result,null,2);status("Providers resolved") }else if(button.id==="upload"){const file=$("#asset").files[0],name=$("#assetName").value.trim();if(!file||!name)throw new Error("Choose a file and asset path");await api("asset?id="+query(state.id)+"&name="+query(name),{method:"PUT",headers:{"Content-Type":"application/octet-stream"},body:file});status("Asset uploaded: "+name)}else if(button.id==="closePreview")$("#previewDialog").close();else if(button.dataset.tab){state.tab=button.dataset.tab;document.querySelectorAll("nav button[data-tab]").forEach(el=>el.classList.toggle("active",el===button));document.querySelectorAll(".tab").forEach(el=>el.classList.toggle("active",el.id===state.tab))}}catch(error){status(error.message,true)}});
window.addEventListener("resize",()=>state.tab==="visual"&&renderVisual());
refreshTemplates().then(async()=>{const first=$(".template");if(first)first.click();else status("Create a template to begin")}).catch(error=>status(error.message,true));
